CREATE DATABASE grocery_store_db;
USE grocery_store_db;

SELECT * FROM suppliers;
SELECT * FROM categories;
SELECT * FROM store_employees;
SELECT * FROM customers;
SELECT * FROM products;
SELECT * FROM orders;
SELECT * FROM orderdetails;

-- 1.How many unique customers have placed orders?
select count(distinct customerid) as uniquecustomers
from orders;

-- 2. Which customers have placed the highest number of orders?
select customerid, COUNT(orderid) AS ordercount
FROM orders
GROUP BY customerid
ORDER BY ordercount DESC;

-- 3.What is the total and average purchase value per customer?
SELECT 
    o.customerID AS customerID,
    SUM(od.PriceEach * od.Quantity) AS TotalAverage,
    AVG(od.PriceEach * od.Quantity) AS AveragePurchase
FROM Orders o
JOIN Orderdetails o ON od.customerID = o.orderID
GROUP BY c.customerID; -- error

-- 4.Who are the top 5 customers by total purchase amount?
SELECT o.customerID,
       SUM(od.PriceEach * od.Quantity) AS TotalPurchase
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY o.customerID
ORDER BY TotalPurchase DESC
LIMIT 5;

## 2. Product Performance
-- 1. How many products exist in each category?
SELECT CategoryID, COUNT(ProductID) AS ProductCount
FROM Products
GROUP BY CategoryID;

-- 2. What is the average price of products by category?
SELECT CategoryID, AVG(Price) AS AvgPrice
FROM Products
GROUP BY CategoryID;

-- 3. Which products have the highest total sales volume (by quantity)?
SELECT ProductID, SUM(Quantity) AS TotalQuantity
FROM OrderDetails
GROUP BY ProductID
ORDER BY TotalQuantity DESC;

-- 4. What is the total revenue generated by each product?
SELECT ProductID, SUM(PriceEach * Quantity) AS Revenue
FROM OrderDetails
GROUP BY ProductID
ORDER BY Revenue DESC;

-- 5. How do product sales vary by category and supplier?
SELECT
    c.CategoryName,
    s.SupplierName,
    SUM(od.Quantity) AS total_quantity_sold,
    SUM(od.PriceEach) AS total_sales_amount
FROM
    OrderDetails od
JOIN products p ON od.ProductID = p.ProductID
JOIN categories c ON p.CategoryID = c.categoryID
JOIN suppliers ON p.SupplierID = s.SupplierID
GROUP BY
    c.CategoryName,
    s.SupplierName
ORDER BY
    c.CategoryName,
    s.SupplierName; -- error
    
## 3. SALES AND ORDER TRENDS
-- 1. How many orders have been placed in total?
SELECT COUNT(OrderID) AS TotalOrders
FROM Orders;

-- 2. What is the average value per order?
SELECT AVG(OrderID) AS Avg_Value_per_Order
FROM (
    SELECT o.OrderID, SUM(od.PriceEach * od.Quantity) AS OrderTotal
    FROM Orders o
    JOIN OrderDetails od ON o.OrderID = od.OrderID
    GROUP BY o.OrderID
) t;

-- 3. On which dates were the most orders placed?
SELECT OrderDate, COUNT(OrderID) AS OrderCount
FROM Orders
GROUP BY OrderDate
ORDER BY OrderCount DESC;

-- 4. What are the monthly trends in order volume and revenue?
SELECT YEAR(OrderDate) AS Year, MONTH(OrderDate) AS Month,
    COUNT(o.OrderID) AS OrderCount,
    SUM(od.PriceEach * od.Quantity) AS Revenue
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY YEAR(OrderDate), MONTH(OrderDate)
ORDER BY Year, Month;

## 4. SUPPLIER CONTRIBUTION
-- 1. How many suppliers are there in the database?
SELECT COUNT(DISTINCT SupplierID) AS SupplierCount
FROM Suppliers;

-- 2. Which supplier provides the most products?
SELECT SupplierID, COUNT(ProductID) AS ProductCount
FROM Products
GROUP BY SupplierID
ORDER BY ProductCount DESC;

-- 3.What is the average price of products from each supplier?
SELECT SupplierID, AVG(Price) AS AvgPrice
FROM Products
GROUP BY SupplierID;

-- 4. Which suppliers contribute the most to total product sales (by revenue)?
SELECT p.SupplierID, SUM(od.PriceEach * od.Quantity) AS Revenue
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.SupplierID
ORDER BY Revenue DESC;

## 5. EMPLOYEE PERFORMANCE
-- 1. How many employees have processed orders?
SELECT COUNT(DISTINCT EmployeeID) AS EmployeeCount
FROM Orders;

-- 2.Which employees have handled the most orders?
SELECT EmployeeID, COUNT(OrderID) AS OrderCount
FROM Orders
GROUP BY EmployeeID
ORDER BY OrderCount DESC;

-- 3. What is the total sales value processed by each employee?
SELECT o.EmployeeID, SUM(od.PriceEach * od.Quantity) AS TotalSales
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY o.EmployeeID
ORDER BY TotalSales DESC;

-- 4. What is the average order value handled per employee?
SELECT employeeID, AVG(OrderValue) AS AvgOrderValue
FROM (
    SELECT o.OrderID, o.employeeID, SUM(od.PriceEach * od.Quantity) AS OrderValue
    FROM Orders o
    JOIN OrderDetails od ON o.OrderID = od.OrderID
    GROUP BY o.OrderID, o.employeeID
) t
GROUP BY employeeID;

## 6. ORDER DETAILS DEEP DIVE
-- 1. What is the relationship between quantity ordered and total price?
SELECT
    od.Quantity,
    SUM(od.Quantity * od.PriceEach) AS total_price
FROM
    orderdetails od
GROUP BY
    od.Quantity
ORDER BY
    od.Quantity;
    
-- 2. What is the average quantity ordered per product?
SELECT
    productid,
    AVG(quantity) AS Average_quantity_ordered
FROM
    orderdetails
GROUP BY
    productid
ORDER BY
    Average_quantity_ordered DESC;
    
-- 3.How does the unit price vary across products and orders?
SELECT
    p.name,
    od.orderid,
    od.PriceEach
FROM
    orderdetails od
JOIN
    products p ON od.productid = p.productid
ORDER BY
    p.name,
    od.orderid; 